"""Initial core memory schema

Revision ID: afc87db0d259
Revises: 
Create Date: 2026-02-27 19:01:39.932915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc87db0d259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_store',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('vector_embedding', sa.Text(), nullable=True),
    sa.Column('semantic_relationship', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('identity_core',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('directive_hash', sa.String(), nullable=False),
    sa.Column('immutable_constraint_blob', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolling_context',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('fifo_blob', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rolling_context')
    op.drop_table('identity_core')
    op.drop_table('fact_store')
    # ### end Alembic commands ###
